export const clues = Object.fromEntries([
  e('lodging-arranged', 'The front rooms', 'Baines kept front rooms for Reed and Ellis at Hale’s request.', 'Baines knows the lodgers by their real surnames, but has not been told they are police. The rear rooms lie beyond the common room and service passage.', 'Mrs Baines, evening conversation', 'lantern-common', 0),
  e('nora-plans', 'Nora’s plans for Bristol', 'Nora is leaving for sewing work arranged by her sister.', 'Nora expects to travel on Saturday. Her sister has found sewing work and a room near her in Bristol. Nora is uncertain about the new work but intends to go.', 'Nora Vale, evening conversation', 'lantern-common', 0),
  e('collection-arranged', 'The morning collection', 'George is paid to carry Nora’s trunk, not Nora herself.', 'Baines arranged the job. George leaves his coal cart in the yard overnight, takes the horse away and will bring it back in the morning. Nora travels separately.', 'George Moss, evening conversation', 'lantern-common', 0),
  e('nora-work', 'The repaired sleeve', 'Nora has nearly finished mending Baines’s sleeve.', 'Nora describes her alteration work and the repair to Baines’s sleeve. The sleeve is finished before she retires.', 'Nora Vale, evening conversation', 'lantern-common', 0),
  paper('inn-newspaper', 'The illustrated report', 'The inn’s complete copy of a sensational illustrated newspaper.', 'The report names wounds to the throat and abdomen. Its imagined illustration shows a scarf across a woman’s face. The complete paper remains at the inn; it is not an eyewitness account.', 'Lantern common-room table', 'lantern-common', 0, 'inn-newspaper'),
  item('opening-sewing', 'An evening’s repair', 'Small, even stitches repair a worn sleeve.', 'The sewing case and sleeve belong to ordinary work in progress at the common-room table.', 'Common-room table, before Nora retires', 'lantern-common', 0, 'opening-sewing'),
  item('opening-trunk', 'Ready for the journey', 'Nora’s large strapped travelling trunk stands ready.', 'A broad, iron-bound travelling trunk rests near the rear service route. It is ordinary luggage prepared for tomorrow’s collection.', 'Lantern, evening', 'lantern-common', 0, 'opening-trunk'),
  item('opening-candlestick', 'The blue-wax candlestick', 'A heavy brass candlestick has a bent loop handle.', 'Blue wax has pooled in its dish. Baines is taking it towards Nora’s rear room.', 'Lantern, evening', 'lantern-common', 0, 'opening-candlestick'),
  item('opening-cart', 'The cart left for morning', 'George’s coal cart stands beside the service entrance.', 'The horse will be stabled elsewhere. The broad steps must remain clear so the luggage can be brought out in the morning.', 'Lantern yard, evening', 'lantern-yard', 0, 'cart-sacks'),
  e('hale-discovery', 'Hale’s discovery account', 'George fetched Hale after finding Nora in the rear yard.', 'Hale found a scarf already arranged across Nora’s face. He summoned Alden, secured the yard and arranged removal on a separate stretcher. The cart and trunk were not used in removal and remain for examination. Alden is available in the mortuary workroom.', 'Constable Hale, account of his attendance', 'lantern-common', 1),
  e('george-discovery', 'George’s morning arrival', 'George says he found Nora before reaching the steps or moving the cart.', 'He brought the horse for the agreed job, left it outside and entered on foot. Baines asked him to check on Nora. He found her in the screened corner and fetched Hale. He says he did not arrange or move the scarf.', 'George Moss, discovery account', 'lantern-yard', 1),
  e('george-night', 'George’s account of the night', 'George denies returning after taking the horse to its stable.', 'He says he noticed no one coming or going, was occupied with the horse, heard nothing from inside and did not return until morning. His account is not an independently witnessed alibi for the whole night.', 'George Moss, account of his own movements', 'lantern-yard', 1),
  e('cart-access', 'The cart stood unguarded', 'Baines confirms that George’s cart remained accessible overnight.', 'George left the cart after his coal delivery and took the horse away. Anyone who entered the yard could reach the sacks. Ownership of the cart does not identify whoever concealed an object there.', 'Mrs Baines, collection and access account', 'baines-room', 1),
  e('george-candlestick', 'George’s answer about the candlestick', 'George denies putting the candlestick under the sacks.', 'He says the cart stood there all night and that he found Nora before moving it. This is his answer to the recovery, not proof of who placed the object under the sacks.', 'George Moss, questioned about the cart', 'lantern-yard', 1),
  e('arthur-brother', 'Arthur’s claimed relationship', 'Arthur says he is Nora’s brother.', 'He uses the claimed relationship to request her belongings. The investigators have not released them to him.', 'Arthur Vale, initial Lantern interview', 'lantern-common', 1),
  e('arthur-visit', 'Arthur’s visit', 'Arthur admits visiting and arguing about Nora’s journey.', 'He says she was packing when he left after a disagreement about Bristol and cannot give an exact time. This records Arthur’s claim; it does not establish it as fact.', 'Arthur Vale, initial Lantern interview', 'lantern-common', 1),
  e('arthur-trunk-denial', 'Arthur’s trunk denial', 'Arthur says he did not touch or carry the trunk.', 'His initial account is a direct denial of moving Nora’s luggage from her room.', 'Arthur Vale, initial Lantern interview', 'lantern-common', 1),
  e('arthur-trunk-reply', 'Arthur’s answer about the trunk', 'Arthur was asked about an unidentified man carrying the trunk.', 'The interview preserves whether Arthur conceded helping with luggage or maintained his denial. Baines did not identify him; her sighting alone cannot contradict that denial.', 'Arthur Vale, follow-up at the Lantern', 'lantern-common', 1),
  e('baines-last-seen', 'Baines’s last ordinary contact with Nora', 'Baines took a candlestick to Nora while she was packing.', 'Nora asked for a candle. Baines mentions the luggage collection arranged for the morning. She does not identify a visitor.', 'Mrs Baines, initial account', 'baines-room', 1),
  e('baines-fear', 'Baines is afraid the man may return', 'Baines fears whoever killed Nora may come back.', 'Questioning reveals her fear but does not establish what she heard or saw. Her suspicion of the Whitechapel murderer is a frightened belief, not an identification.', 'Mrs Baines, questions about the night', 'baines-room', 1),
  e('hale-private-recovery', 'Hale keeps the search private', 'Arthur is kept at the front, away from the search and witness interviews.', 'Hale controls the rear passage. The detectives inspect the yard privately; George is questioned there and Baines in her own room. Neither witness is allowed to speak to Arthur. Recovery details are not discussed in his hearing.', 'Constable Hale, access arrangements before the search', 'lantern-common', 1),
  item('courtyard-knife', 'The knife recovered beside Nora', 'Hale found an ordinary knife openly beside Nora in the courtyard.', 'Hale recovered the knife before the stretcher arrived and retains it wrapped for examination. Its owner is unknown. Its presence does not establish what killed Nora.', 'Constable Hale, recovery and custody account', 'lantern-yard', 1, 'courtyard-knife'),
  e('hale-protection', 'A constable watches the back steps', 'Hale arranges for a constable to watch the back steps while Baines speaks.', 'A constable watches the steps throughout the enquiry while Hale remains with Arthur at the front. The detectives can tell Baines what has actually been arranged.', 'Constable Hale, protection arrangement', 'lantern-common', 1),
  e('baines-reassured', 'Baines agrees to speak', 'Baines agrees to talk after hearing that a constable is watching the steps.', 'She asks to sit away from the passage with the door shut. No night observations are recorded until she gives them.', 'Mrs Baines, reassurance', 'baines-room', 1),
  e('baines-disturbance', 'Voices, a cry and a thud', 'Baines heard voices, then a cry and a thud from the rear rooms.', 'She could not make out the words or identify the speakers. She stayed in her room and did not open her door.', 'Mrs Baines, account given after reassurance', 'baines-room', 1),
  e('baines-trunk', 'An unidentified man carried the trunk', 'Baines glimpsed a man carrying Nora’s trunk down the steps after the disturbance.', 'She looked from her window. The man was turned away and she could not see his face. This statement does not identify Arthur, George or the Whitechapel murderer.', 'Mrs Baines, window account', 'baines-room', 1),
  e('baines-hiding', 'Baines bolted her door and hid', 'Baines withdrew from the window and hid after seeing the man.', 'She feared he might be the Whitechapel murderer. She did not see what he did in the screened yard or what the trunk contained. There was no encounter or spoken threat.', 'Mrs Baines, explanation of hiding', 'baines-room', 1),
  e('blanket-identification', 'Nora’s bed blanket', 'Baines identifies the stained blanket from the trunk as Nora’s bedding.', 'She recognizes the blue edging and a repair near one corner. The same blanket was on Nora’s bed, where it is now missing.', 'Mrs Baines, shown the trunk bedding', 'baines-room', 1),
  e('candlestick-description', 'The missing bedside candlestick', 'Baines describes the heavy candlestick she lent Nora.', 'It stood beside Nora’s bed. Its loop handle is bent and its dish holds blue wax. A description alone does not prove which object was used in an attack.', 'Mrs Baines, room furnishings account', 'baines-room', 1),
  e('candlestick-identification', 'Baines identifies the candlestick', 'Baines recognizes the bent handle and blue wax on the recovered candlestick.', 'The object recovered under the coal sacks is the candlestick she put beside Nora’s bed. Baines does not know who carried it into the yard.', 'Mrs Baines, shown the recovered object', 'baines-room', 1),
  e('workshop-lead', 'Maggie Shaw’s workshop', 'Maggie Shaw can be found at the garment workshop.', 'The source of this lead is preserved in the discovery record: Baines’s directions or the work note in Nora’s room. Maggie worked with Nora.', 'Lantern enquiries or Nora’s work correspondence', 'nora-room', 1),
  paper('work-correspondence', 'Maggie’s work note', 'A note in Nora’s room names Maggie Shaw’s garment workshop.', 'Maggie kept Nora’s unfinished work and said she would be at the long table by the workshop window.', 'Nora’s rear room', 'nora-room', 1, 'work-correspondence'),
  item('trunk-interior', 'The stained trunk interior', 'Loose clothes concealed stained bedclothes and lining.', 'The deep trunk is large enough for a curled adult. Dark blood stains mark the blanket and lining beneath a few clothes. Its contents and Hale’s separate-removal account must be considered together.', 'Trunk beside the Lantern service entrance', 'lantern-yard', 1, 'trunk-bedding'),
  item('cart-candlestick', 'Candlestick beneath the sacks', 'A heavy brass candlestick lay hidden in George’s coal cart.', 'The loop handle is bent and blue wax fills the dish. This records the recovery place and appearance, not the owner or who concealed it.', 'Beneath a coal sack in George’s cart', 'lantern-yard', 1, 'candlestick-recovered'),
  item('yard-discovery', 'The screened discovery corner', 'Very little blood remains at the discovery spot.', 'The projecting washhouse screens this corner from Baines’s window. Nora and her scarf have been removed; the scarf is retained with her effects.', 'Lantern yard, after official removal', 'lantern-yard', 1, 'yard-discovery'),
  item('room-disturbance', 'Interrupted packing and concealed blood', 'Clothes lie emptied by the bed and blood is hidden beneath the rug.', 'A blanket is missing from the bed. The rug has been shifted over a dark blood stain. These are observations of a disturbance; the identity of the person responsible remains to be established.', 'Nora’s rear room', 'nora-room', 1, 'room-blood'),
  paper('torn-wedding', 'Nora’s torn wedding photograph', 'A wedding portrait has been torn through the person beside Nora.', 'Nora and her mother remain. The reverse reads “Our wedding · 8 June 1884”. The surviving photograph does not identify the removed groom.', 'Inside Nora’s sewing case', 'nora-room', 1, 'torn-wedding'),
  paper('travel-papers', 'The ticket, sleeve and sister’s letter', 'Nora had prepared a Saturday journey to Bristol.', 'The ordinary ticket is for the Bristol journey. The handwritten sleeve is addressed to Nora Finch; the sister’s letter offers sewing work and explains that Finch was used at Nora’s request.', 'Nora’s travelling papers', 'nora-room', 1, 'travel-papers'),
  item('service-route', 'The short service route', 'A short landing and a few broad steps connect the rear rooms to the yard.', 'The route is wide enough for Nora’s large trunk. This establishes a possible route, not who used it.', 'Rear landing of the Lantern', 'baines-room', 1, 'service-route'),
  item('window-view', 'What Baines’s window overlooks', 'The landing and upper steps are visible, but the discovery corner is screened.', 'The projecting washhouse blocks the far corner. Baines could see a trunk being carried down without seeing its contents or what happened beyond the washhouse.', 'View from Baines’s rear window', 'baines-room', 1, 'window-view'),
  paper('medical-findings', 'Alden’s medical findings', 'The blunt head injury was fatal; the knife wounds were inflicted after death.', 'Alden establishes the head injury as fatal and the throat and abdominal wounds as post-mortem. He cannot identify a unique weapon or offender, or give a precise hour of death.', 'Dr William Alden, explanation and signed account', 'alden-workroom', 1, 'medical-findings'),
  e('alden-knife', 'Alden on the recovered knife', 'The knife recovered beside Nora does not change Alden’s findings.', 'Alden confirms the knife wounds were inflicted after death and cannot identify a particular knife from them.', 'Dr Alden, discussion after Hale’s knife recovery', 'alden-workroom', 1),
  e('alden-movement', 'Alden on the room and trunk', 'Alden considers the traces consistent with injury indoors and subsequent movement.', 'The room blood and stained bedding support movement when read with the discovery account. His medical opinion does not identify the person who moved Nora.', 'Dr Alden, shown the room and trunk observations', 'alden-workroom', 1),
  e('alden-candlestick', 'The blunt-object comparison', 'Alden says the candlestick is consistent with a hard, blunt blow.', 'He cannot uniquely identify this object as the cause of Nora’s head injury. The blunt head injury was fatal. Compatibility alone does not uniquely identify the candlestick as the weapon.', 'Dr Alden, shown the recovered candlestick', 'alden-workroom', 1),
  e('maggie-cooperation', 'Maggie agrees to speak', 'Maggie agrees to speak privately after asking whether Arthur is present.', 'Maggie helped Nora with preparations and was asked to keep quiet until Nora was away. The investigators establish that Arthur has not come with them and close the workshop door.', 'Maggie Shaw, initial workshop conversation', 'shaw-workshop', 1),
  paper('finch-work-card', 'The earlier Finch work card', 'Maggie’s older work card names Nora Finch before the wedding.', 'Maggie explains that Finch was Nora’s family name. Maggie names Arthur Vale as Nora’s husband. Nora was returning to Finch for the Bristol journey.', 'Maggie Shaw’s workshop accounts', 'shaw-workshop', 1, 'finch-work-card'),
  e('marriage-identification', 'Maggie identifies the marriage', 'Maggie says Arthur Vale was Nora’s husband, not her brother.', 'She says she attended Nora and Arthur’s wedding. Her testimony establishes the marriage independently of examining the photograph. She is Nora’s friend and fellow worker; Nora’s sister lives in Bristol.', 'Maggie Shaw, first-hand knowledge of the marriage', 'shaw-workshop', 1),
  paper('complete-wedding', 'The complete wedding photograph', 'Arthur appears beside Nora in Maggie’s complete print.', 'The reverse names Nora Finch and Arthur Vale and gives their wedding date. Maggie identifies the couple and occasion while handing over her print; it can also be compared with the torn print if found.', 'Maggie Shaw’s own keepsake, handed over for examination', 'shaw-workshop', 1, 'complete-wedding'),
  e('maggie-separation', 'Why Nora left', 'Maggie helped Nora leave Arthur and prepare for work near her sister.', 'Maggie says Arthur took Nora’s wages and checked where she went. Nora decided to leave. They had shared the upstairs room above Bell’s boot-repair shop, off Commercial Road. Maggie did not witness the killing.', 'Maggie Shaw, account of helping Nora', 'shaw-workshop', 1),
  e('address-verified', 'Hale’s address verification', 'Hale confirms Arthur still occupies the room Maggie described.', 'The landlord at Bell’s boot-repair shop confirms Arthur’s current occupancy. This verifies where a search can be arranged; it supplies no prediction of what will be found.', 'Constable Hale, relaying the checking officer’s report', 'lantern-common', 1),
  item('unfinished-work', 'Nora’s unfinished allocation', 'Careful seams stop partway through a pile of shirts.', 'The remaining allocation was left for the workshop when Nora prepared to travel. It supplies context for her trade and ordinary plans.', 'Maggie’s garment workshop', 'shaw-workshop', 1, 'unfinished-work'),
  item('hearth-clothing', 'Burned clothing', 'Woollen clothing has been burned among the hearth remains.', 'Stained cloth remains among the ash. This observation does not identify a particular stain by scientific test. The remains do not identify a particular wearer or a particular source of the stains.', 'Arthur’s hearth', 'vale-room', 2, 'hearth-clothing'),
  paper('burned-report', 'Arthur’s burned report', 'A partly burned copy retains the dated report and scarf illustration.', 'The legible portion can be compared with the complete newspaper at the inn. It is another copy, not a fragment removed from the inn paper.', 'Arthur’s hearth, among burned paper', 'vale-room', 2, 'burned-report'),
  ...[
    ['station-relationship', 'Arthur’s relationship explanation', 'Arthur was questioned about concealing his marriage.'],
    ['station-trunk', 'Arthur’s account of the contents', 'Arthur was questioned about the stained trunk and his earlier answer.'],
    ['station-fire', 'Arthur’s answer about the fire', 'Arthur was questioned about the clothing and newspaper he burned.'],
    ['station-knowledge', 'Arthur’s answer about the unshared detail', 'Arthur was confronted after Hale’s account contradicted his claimed source.'],
    ['station-room', 'Arthur’s account of the room', 'Arthur was asked what happened during his visit to Nora’s room.'],
    ['station-cause', 'The fatal-injury allegation', 'Arthur’s account was tested against the medical findings and the disturbance.'],
    ['station-yard', 'Arthur’s account of the yard', 'The allegation that the yard was arranged to suggest another murder was put to Arthur.'],
  ].map(([id, title, description]) => e(id, title, description, 'The saved interview preserves the exact response obtained. This subject record does not assert an admission beyond those words.', 'Arthur Vale, Commercial Street interview', 'station-interview', 3)),
  e('arthur-candlestick-slip', 'Arthur names the hiding place', 'Arthur says the candlestick was under the sacks in George’s cart.', 'Told only that the candlestick had been recovered, Arthur directs suspicion at George and volunteers the concealed location. This is evidence of knowledge, not an explicit confession to killing Nora.', 'Arthur Vale, recovered-candlestick question', 'station-interview', 3),
  e('arthur-source-claim', 'Arthur says an officer told him', 'Arthur claims one of the officers told him where the candlestick was found.', 'He cannot name the officer and says someone told him rather than that he overheard it. This excuse remains to be checked with Hale.', 'Arthur Vale, question about his source', 'station-interview', 3),
  e('hale-disclosure-check', 'Hale checks who spoke to Arthur', 'Hale says he did not disclose the candlestick’s hiding place to Arthur.', 'Hale accounts for Arthur’s access and contacts: the removal officers left before Arthur arrived, Hale alone spoke to and escorted him, the yard and address officers kept away from him, and witness interviews and the search were kept separate. Read this with Arthur’s specific claim and the detectives’ own private questioning.', 'Constable Hale, Commercial Street follow-up', 'station-interview', 3),
  e('arthur-fall', 'Arthur claims Nora fell', 'Arthur changes his account and says he took Nora’s arm before she fell.', 'He claims she pulled away and struck the washstand, then says he thought she was dead. This contradicts his earlier account of leaving her packing; it does not establish that her death was accidental.', 'Arthur Vale, return to the argument', 'station-interview', 3),
  e('scarf-admitted', 'Arthur admits moving Nora and covering her face', 'Arthur says he moved Nora in the trunk and covered her face in the yard.', 'He claims he was frightened and could not bear to look at her. This admission does not yet acknowledge an intention to imitate the murders.', 'Arthur Vale, movement follow-up', 'station-interview', 3),
  e('disguise-admitted', 'Arthur’s account of the disguise', 'Arthur admits wanting the arrangement in the yard to suggest another Whitechapel murder.', 'He acknowledges hoping the arrangement would divert blame to the other murderer, but refuses to discuss the knife and insists Nora fell. His last answer denies killing her. This is a limited admission to disguise, not a confession to the fatal blow.', 'Arthur Vale, yard follow-up', 'station-interview', 3),
  e('arthur-found-nora', 'How Arthur found the Lantern', 'Arthur says he followed Nora from the workshop on Friday.', 'He says Nora did not know he was following her and that he learned about Bristol when he went to her room. This records his account of finding her, not an admission to the killing.', 'Arthur Vale, Commercial Street interview', 'station-interview', 3),
  e('arthur-departure', 'Arthur wanted Nora to return', 'Arthur says he wanted Nora to come home.', 'He says Nora asked him to leave, but he stayed to talk. He blames her decision to leave or her sister’s encouragement; the detectives put Nora’s own plans to him.', 'Arthur Vale, departure question', 'station-interview', 3),
  e('closing-addressed', 'The people waiting at the Lantern', 'An investigator has spoken with someone left waiting for news.', 'The closing conversation remains in the shared interview record. Nora’s belongings remain secured as evidence pending arrangements with her sister.', 'Closing conversations at the Lantern', 'lantern-common', 4),
  paper('closing-letter', 'Maggie writes to Nora’s sister', 'Maggie’s letter turns to Nora’s belongings and interrupted journey.', 'The letter says the enquiry is complete without inventing an admission from Arthur. Maggie will help return Nora’s things when they may be released.', 'Maggie Shaw, common-room table', 'lantern-common', 4, 'closing-letter'),
].map(record => [record.id, record]));

export const objects = Object.fromEntries([
  object('opening-trunk', 'The travelling trunk', 'lantern-inn', 'opening-trunk', 'opening-trunk', [step('ready', 'Examine the ready luggage', 'A broad travelling trunk with iron bands and leather straps.', 'opening-trunk')], [reward('opening-trunk', ['ready'])]),
  object('opening-cart', 'The cart for morning', 'lantern-inn', 'opening-cart', 'cart-sacks', [step('cart', 'Look over the coal cart', 'Coal sacks lie across the bed of the cart.', 'cart-sacks')], [reward('opening-cart', ['cart'])]),
  object('opening-sewing', 'The evening repair', 'lantern-inn', 'opening-sewing', 'opening-sewing', [step('repair', 'Examine the repaired sleeve', 'Small, even stitches mend Mrs Baines’s worn sleeve. Nora’s needles and thread lie beside it.', 'opening-sewing')], [reward('opening-sewing', ['repair'])]),
  object('opening-candlestick', 'The borrowed candlestick', 'lantern-inn', 'opening-candlestick', 'opening-candlestick', [step('handle', 'Look at the candlestick', 'The brass loop handle is bent and blue wax fills the dish.', 'opening-candlestick')], [reward('opening-candlestick', ['handle'])]),
  object('work-correspondence', 'Nora’s work correspondence', 'lantern-inn', 'workshop-lead', 'work-correspondence-original', [step('read', 'Read Maggie’s work note', 'Maggie has kept Nora’s unfinished seams at Shaw’s garment workshop. She can be found at the long table by the window.', 'work-correspondence-original')], [reward('work-correspondence', ['read'], false), reward('workshop-lead', ['read'], false)]),
  object('trunk', 'Nora’s travelling trunk', 'lantern-inn', 'trunk-interior', 'trunk-closed', [
    step('open', 'Open the trunk', 'A few travelling clothes lie loosely across the top.', 'trunk-open'),
    step('lift-clothes', 'Lift the loose clothes', 'Stained bedclothes cover the bottom of the deep trunk.', 'trunk-bedding', ['open']),
  ], [reward('trunk-interior', ['open', 'lift-clothes'])]),
  object('cart-candlestick', 'Coal cart and sacks', 'lantern-inn', 'cart-candlestick', 'cart-sacks', [
    step('sacks', 'Examine the coal sacks', 'One sack sags over a hard object near the side of the cart.', 'cart-sacks'),
    { ...step('lift-sack', 'Lift the sack', 'A brass candlestick lies beneath it. The loop handle is bent; blue wax remains in the dish.', 'candlestick-recovered', ['sacks']), requiresEvidence: ['hale-private-recovery'], blockedMessage: 'Ask Hale to keep the search private before lifting the sacks.' },
  ], [reward('cart-candlestick', ['sacks', 'lift-sack'])]),
  object('room-disturbance', 'The interrupted packing', 'lantern-inn', 'room-disturbance', 'room-packing', [
    step('bed', 'Examine the bed and clothes', 'Clothes have been emptied beside the bed. Its blanket is missing and the rug is displaced.', 'room-packing'),
    step('rug', 'Lift the edge of the rug', 'Dark blood marks the floor beneath the rug.', 'room-blood', ['bed']),
  ], [reward('room-disturbance', ['bed', 'rug'])]),
  object('sewing-case', 'Nora’s sewing case', 'lantern-inn', 'torn-wedding', 'sewing-case', [
    step('lid', 'Open the sewing case', 'Thread, needles and cloth scraps surround a torn photograph in the lid.', 'sewing-case'),
    step('portrait', 'Examine the photograph', 'Nora and her mother remain. The person beside the bride has been torn away.', 'torn-wedding-front', ['lid']),
    step('reverse', 'Turn the photograph over', 'The remaining writing reads: “Our wedding · 8 June 1884”. No groom’s name remains.', 'torn-wedding-back', ['portrait']),
  ], [reward('torn-wedding', ['lid', 'portrait', 'reverse'], false)]),
  object('service-route', 'Landing and window', 'lantern-inn', 'service-route', 'service-route', [
    step('landing', 'Follow the route to the yard', 'A short service landing and three broad, shallow steps can accommodate the large trunk.', 'service-route'),
    step('window', 'Look from Baines’s window', 'The landing and upper steps are visible. The projecting washhouse screens the discovery corner.', 'window-view'),
  ], [reward('service-route', ['landing']), reward('window-view', ['window'])], ['window-view']),
  object('hearth-remains', 'Arthur’s cold hearth', 'vale-lodgings', 'hearth-clothing', 'hearth-surface', [
    step('surface', 'Examine the hearth surface', 'Burned woollen clothing and partly burned paper remain among the ash.', 'hearth-surface'),
    step('cloth', 'Separate the burned clothing', 'Stained woollen scraps remain among the ash.', 'hearth-clothing', ['surface']),
    { ...step('paper', 'Unfold the surviving newspaper', 'The title, date and scarf illustration remain legible on a partly burned report.', 'burned-report-original', ['surface']), togetherAt: 'vale-room', blockedMessage: 'Bring both investigators to help unfold the fragile newspaper.' },
  ], [reward('hearth-clothing', ['cloth']), reward('burned-report', ['paper'], false)]),
  object('unfinished-work', 'Work left behind', 'shaw-workshop', 'unfinished-work', 'unfinished-work', [
    step('seams', 'Examine the unfinished seams', 'Small, even stitches stop partway across the shirts.', 'unfinished-work'),
  ], [reward('unfinished-work', ['seams'])]),
].map(record => [record.id, record]));

export const deductions = [
  d('trunk-movement', 'The trunk carried out at night', 'Why was Nora’s trunk carried out during the night?', ['baines-trunk', 'trunk-interior'], 'The man carried the trunk after an indoor disturbance. Its stained bedding and lining, with the room traces, support moving Nora into the yard. This raises a question about concealment behind the apparent street murder. It neither identifies the man nor rules out the Whitechapel murderer.', { requiresDeduction: 'room-to-yard' }),
  d('room-to-yard', 'Movement from room to yard', 'Was Nora moved from her room?', ['room-disturbance', 'trunk-interior'], 'Blood beneath the rug, emptied packing and stained trunk bedding support movement from the room to the yard. Baines identifies the missing blanket and the inspected service route can accommodate the trunk.', { requiresAll: ['blanket-identification', 'service-route', 'hale-discovery'] }),
  d('concealed-marriage', 'The concealed marriage', 'Who was Arthur to Nora?', ['complete-wedding', 'arthur-brother'], 'The complete wedding print and Maggie’s identification establish that Arthur was Nora’s husband. His morning brother claim concealed that relationship while he sought control of her belongings. Baines did not admit him under that claim the night before.', { requiresChoice: { id: 'marriage-identified', value: 'confirmed' } }),
  d('candlestick-origin', 'The missing candlestick recovered', 'Where did the candlestick in the cart come from?', ['cart-candlestick', 'candlestick-identification'], 'Baines identifies the recovered candlestick as the one she placed in Nora’s room. Its recovery proves concealment in the cart, not that George hid or used it.', { requiresAll: ['cart-access'] }),
  d('disturbance-sequence', 'After the disturbance', 'What did Baines hear and see?', ['baines-disturbance', 'baines-trunk'], 'Baines heard voices, a cry and a thud, later glimpsed an unidentified man carrying Nora’s trunk, then bolted her door and hid. The observations support a sequence, not the carrier’s identity or an eyewitness account of the killing.', { requiresDeduction: 'room-to-yard', requiresAll: ['window-view', 'baines-hiding'] }),
  d('report-edition', 'Another copy of the same report', 'Which report did Arthur possess?', ['burned-report', 'inn-newspaper'], 'The surviving masthead, date, text and illustration identify another copy of the same edition. The inn’s complete copy never left the common room. Ownership alone does not prove murder or imitation.'),
  d('false-knife', 'The misleading knife', 'Did the knife beside Nora cause her death?', ['courtyard-knife', 'medical-findings'], 'The openly placed knife and visible wounds suggest a knife killing. Alden establishes that the blunt head injury killed Nora and that the knife wounds were made after death. This distinguishes the fatal assault from the later injuries; the arrangement’s purpose and its author require further evidence.'),
  d('unshared-detail', 'Arthur knows the hiding place', 'What did Arthur know that the detectives had not told him?', ['arthur-candlestick-slip', 'cart-candlestick'], 'Arthur volunteered that the candlestick was under the sacks in George’s cart. The detectives had disclosed only its recovery. His accurate description of the concealed location requires an explanation; it is not itself a complete confession.', { requiresAll: ['hale-private-recovery', 'candlestick-identification'] }),
  d('source-excuse', 'The officer explanation fails', 'Does Hale’s account support Arthur’s claimed source?', ['arthur-source-claim', 'hale-disclosure-check'], 'Arthur says an officer told him where the candlestick was found. Hale accounts for his contacts and confirms that no such disclosure occurred. Combined with the private search and witness interviews, this undermines Arthur’s explanation of his knowledge. It strengthens the cumulative case without supplying an admission to the fatal blow.', { requiresDeduction: 'unshared-detail' }),
  d('staged-resemblance', 'The apparent Whitechapel connection', 'What might explain the arrangement in the yard?', ['inn-newspaper', 'hale-discovery'], 'The scarf arrangement recalls the paper’s invented illustration; Alden establishes post-mortem knife wounds, and George denies arranging the scarf. Arthur’s burned copy supplies a source for imitation. Read with the independent case against him, deliberate staging is supported as an inference, not a medical certainty or identification of the historical murderer.', { requiresDeduction: 'report-edition', requiresAll: ['burned-report', 'medical-findings', 'courtyard-knife', 'george-discovery'] }),
];

export const reconstructions = [{
  id: 'disturbance-sequence', title: 'What Baines could establish',
  instruction: 'Arrange only what Baines heard, saw and did. She could not identify the man.',
  pairs: [['baines-disturbance', 'baines-trunk']],
  events: [
    { id: 'trunk', label: 'Later, an unidentified man carries Nora’s trunk down the steps.' },
    { id: 'hide', label: 'Baines withdraws, bolts her door and hides.' },
    { id: 'cry', label: 'Baines hears voices, a cry and a thud from the rear rooms.' },
  ],
  order: ['cry', 'trunk', 'hide'],
  failure: 'Baines heard the disturbance, later saw the man with the trunk, then bolted her door and hid. She did not identify him.',
}];

function e(id, title, description, detail, provenance, location, chapter) { return { id, title, description, detail, provenance, location, chapter, kind: 'testimony' }; }
function item(id, title, description, detail, provenance, location, chapter, image) { return { ...e(id, title, description, detail, provenance, location, chapter), kind: 'object', image }; }
function paper(id, title, description, detail, provenance, location, chapter, documentId) { return { ...e(id, title, description, detail, provenance, location, chapter), kind: 'object', documentId }; }
function step(id, label, observation, image, requires) { return { id, label, observation, image, ...(requires ? { requires } : {}) }; }
function reward(id, steps, reviewAsObject = true) { return { id, chapter: clues[id].chapter, steps, reviewAsObject }; }
function object(id, title, siteId, hotspot, initial, steps, evidence, extraHotspots = []) {
  return { id, title, model: 'box', color: '#61523e', siteId, hotspots: [hotspot, ...extraHotspots], views: { initial, steps: Object.fromEntries(steps.map(step => [step.id, { image: step.image, point: inspectionPoints(id)[step.id] }])) }, steps: steps.map(({ image, ...step }) => step), evidence };
}
function d(id, title, question, requires, explanation, gates = {}) { return { id, title, question, requires, explanation, ...gates }; }

function inspectionPoints(id) {
  return {
    "opening-trunk": {"ready": [50, 45]},
    "opening-cart": {"cart": [50, 37]},
    "opening-sewing": {"repair": [40, 60]},
    "opening-candlestick": {"handle": [67, 59]},
    "work-correspondence": {"read": [50, 50]},
    "trunk": {"open": [50, 44], "lift-clothes": [49, 53]},
    "cart-candlestick": {"sacks": [49, 38], "lift-sack": [57, 36]},
    "room-disturbance": {"bed": [28, 37], "rug": [62, 64]},
    "sewing-case": {"lid": [53, 37], "portrait": [55, 32], "reverse": [55, 65]},
    "service-route": {"landing": [62, 65], "window": [28, 42]},
    "hearth-remains": {"surface": [50, 55], "cloth": [42, 66], "paper": [65, 72]},
    "unfinished-work": {"seams": [50, 49]},
  }[id];
}
