import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

const origin = process.env.FRAMEWORK_ORIGIN ?? 'http://127.0.0.1:5288';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const errors = [];
await mkdir('.qa/framework', { recursive: true });
const contexts = await Promise.all([browser.newContext({ viewport: { width: 1440, height: 1000 } }), browser.newContext({ viewport: { width: 1100, height: 850 }, reducedMotion: 'reduce' })]);
const [one, two] = await Promise.all(contexts.map(context => context.newPage()));
for (const page of [one, two]) page.on('pageerror', error => errors.push(error.message));
const story = await (await fetch(`${origin}/api/story`)).json();
const credentials = page => page.evaluate(story => { const prefix = `investigation.v5.${story.id}.${story.version}.`; return JSON.parse(localStorage.getItem(prefix + localStorage.getItem(prefix + 'last'))); }, story);
async function request(player, path, body) {
  const response = await fetch(`${origin}/api/cases/${player.roomId}${path}`, { method: body ? 'POST' : 'GET', headers: { 'Content-Type': 'application/json', 'X-Player-Id': player.playerId, Authorization: `Bearer ${player.secret}` }, ...(body ? { body: JSON.stringify(body) } : {}) });
  assert.equal(response.ok, true, await response.clone().text());
  return response.json();
}
const act = (player, action) => request(player, '/actions', { requestId: crypto.randomUUID(), action });
const snapshot = player => request(player, '');

try {
  await one.goto(origin);
  await one.getByRole('button', { name: 'Play with a partner', exact: true }).click();
  await expect(one.getByRole('heading', { name: 'Choose your inspector' })).toBeVisible();
  const first = await credentials(one);
  assert.equal((await snapshot(first)).phase, 'lobby');
  assert.equal((await act(first, { type: 'travel', location: 'preview-common' })).ok, false);
  await one.getByRole('button', { name: /Inspector Reed Short/ }).click();
  await one.getByRole('button', { name: 'I’m ready' }).click();
  assert.equal((await snapshot(first)).phase, 'lobby');
  await one.screenshot({ path: '.qa/framework/lobby.png' });
  await one.setViewportSize({ width: 390, height: 844 });
  assert.ok(await one.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await one.screenshot({ path: '.qa/framework/lobby-mobile.png', fullPage: true });
  await one.setViewportSize({ width: 1440, height: 1000 });
  await two.goto(`${origin}/?case=${first.roomId}`);
  await two.getByRole('button', { name: 'Join your partner', exact: true }).click();
  await expect(two.getByRole('heading', { name: 'Choose your inspector' })).toBeVisible();
  const second = await credentials(two);
  assert.equal((await act(second, { type: 'selectInspector', inspector: 'reed' })).ok, false);
  await two.getByRole('button', { name: /Inspector Ellis Very tall/ }).click();
  await two.getByRole('button', { name: 'I’m ready' }).click();
  if (story.id === 'starter') {
    await expect(one.getByRole('heading', { name: 'Empty scene', exact: true })).toBeVisible();
    const shell = await snapshot(first);
    assert.equal(shell.phase, 'investigating');
    assert.equal(shell.locations.length, 1);
    for (const key of ['evidence', 'npcs', 'questions', 'deductions']) assert.deepEqual(shell[key], []);
    assert.deepEqual(shell.objects, {});
    assert.deepEqual(story.assets, {});
    assert.equal((await fetch(`${origin}/story-assets/whitechapel/1/letter.png`)).status, 404);
    await expect(one.locator('.world-3d[data-ready=true] canvas')).toBeVisible({ timeout: 20000 });
    await one.screenshot({ path: '.qa/framework/empty-shell.png' });
    await one.setViewportSize({ width: 390, height: 844 });
    assert.ok(await one.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await one.screenshot({ path: '.qa/framework/empty-shell-mobile.png' });
    for (const page of [one, two]) {
      await page.getByRole('button', { name: 'Case map', exact: true }).click();
      await page.getByRole('button', { name: 'Finish', exact: true }).click();
      await page.getByRole('dialog').getByRole('button', { name: 'Finish', exact: true }).click();
    }
    await expect(one.getByRole('heading', { name: 'Case complete', exact: true })).toBeVisible();
    assert.equal((await snapshot(first)).phase, 'solved');
    console.log('Starter passed: two-player lobby, empty scene, no campaign data or assets, responsive layout and joint completion.');
  } else {
  for (const page of [one, two]) await expect(page.getByText('A short demonstration. This is not the new story.', { exact: true })).toBeVisible();
  assert.equal((await snapshot(first)).phase, 'cutscene');
  assert.equal((await act(first, { type: 'continueStage' })).ok, false);
  const old = (await snapshot(first)).cutscene;
  await one.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(one.getByText('Waiting for your partner.', { exact: true })).toBeVisible();
  assert.equal((await snapshot(first)).cutscene.index, 0);
  await two.getByRole('button', { name: 'Continue', exact: true }).click();
  for (const page of [one, two]) await expect(page.getByText('Ready, Inspector Ellis?', { exact: true })).toBeVisible();
  await one.screenshot({ path: '.qa/framework/shot.png' });
  await one.setViewportSize({ width: 390, height: 844 });
  await expect(one.getByRole('button', { name: 'Continue', exact: true })).toBeInViewport();
  await one.screenshot({ path: '.qa/framework/shot-mobile.png' });
  await one.setViewportSize({ width: 1440, height: 1000 });
  assert.equal((await act(first, { type: 'cutscene', command: { type: 'advance', runId: old.runId, index: 0 } })).ok, false);
  await two.goto('about:blank');
  await expect(one.getByText('Waiting for both inspectors to reconnect.', { exact: true })).toBeVisible();
  await one.reload();
  await expect(one.getByText('Waiting for both inspectors to reconnect.', { exact: true })).toBeVisible();
  assert.equal((await snapshot(first)).cutscene.index, 1);
  await two.goto(`${origin}/?case=${first.roomId}`);
  for (const page of [one, two]) await expect(page.getByText('Ready, Inspector Ellis?', { exact: true })).toBeVisible();
  await one.getByRole('button', { name: 'Continue', exact: true }).click();
  await two.getByRole('button', { name: 'Continue', exact: true }).click();
  for (const page of [one, two]) await expect(page.getByText('After you, Inspector Reed.', { exact: true })).toBeVisible();
  await one.getByRole('button', { name: 'Skip scene together' }).click();
  assert.equal((await snapshot(first)).phase, 'cutscene');
  await two.getByRole('button', { name: 'Agree to skip scene' }).click();
  await expect(one.getByRole('article', { name: 'Document transcription' })).toBeVisible();
  await one.getByRole('button', { name: 'Second page', exact: true }).click();
  await expect(one.getByText('This is a reader test, not story content.', { exact: true })).toBeVisible();
  await one.getByRole('button', { name: 'View original', exact: true }).click();
  await one.screenshot({ path: '.qa/framework/document.png' });
  for (const page of [one, two]) await page.getByRole('button', { name: 'Begin the enquiry', exact: true }).click();
  await expect(one.getByRole('button', { name: 'Case map', exact: true })).toBeVisible();
  for (const page of [one, two]) {
    await page.getByRole('button', { name: 'Case map', exact: true }).click();
    await page.getByRole('button', { name: 'Retire for the evening', exact: true }).click();
    await page.getByRole('dialog').getByRole('button', { name: 'Retire for the evening', exact: true }).click();
  }
  await expect(one.getByText('The inspectors return to the yard.', { exact: true })).toBeVisible();
  await one.getByRole('button', { name: 'Skip scene together' }).click();
  await two.getByRole('button', { name: 'Agree to skip scene' }).click();
  await expect.poll(async () => (await snapshot(first)).chapter.index).toBe(1);
  const district = await snapshot(first);
  assert.equal(district.locations.length, 6);
  await one.getByRole('button', { name: 'Explore', exact: true }).click();
  await expect(one.getByRole('button', { name: 'Open district map' })).toHaveCount(0);
  await expect(one.locator('.location-list > button')).toHaveCount(6);
  await one.screenshot({ path: '.qa/framework/six-destinations.png' });
  await one.setViewportSize({ width: 390, height: 844 });
  assert.ok(await one.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await expect(one.getByRole('button', { name: 'Open district map' })).toHaveCount(0);
  await one.screenshot({ path: '.qa/framework/destinations-mobile.png' });
  await one.setViewportSize({ width: 1440, height: 1000 });
  for (const place of district.locations) assert.equal((await act(first, { type: 'travel', location: place.id })).ok, true);
  assert.equal((await act(first, { type: 'travel', location: 'not-a-place' })).ok, false);
  assert.ok(district.objects.sample.steps.every(step => step.observation === ''));
  assert.equal('chapters' in story, false);
  assert.equal('reconstructions' in story, false);
  assert.equal((await act(first, { type: 'finalReport', findings: ['together', 'six-places'] })).ok, false);
  await act(first, { type: 'travel', location: 'preview-workshop' });
  await one.getByRole('button', { name: /^Curator/ }).click();
  await expect(one.getByText('I have the sample record ready.', { exact: true })).toBeVisible({ timeout: 20000 });
  await one.getByRole('button', { name: 'Continue', exact: true }).click();
  // The authored fixture uses the gateway; production interviews use spoken input.
  assert.equal((await act(first, { type: 'ask', npcId: 'curator', topicId: 'record' })).ok, true);
  await expect(one.getByText('May we see the record?', { exact: true })).toBeVisible();
  await one.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(one.getByText('I checked the sample on arrival.', { exact: true })).toBeVisible();
  await one.getByRole('button', { name: 'Continue', exact: true }).click();
  await one.getByRole('button', { name: 'End conversation', exact: true }).click();
  await act(first, { type: 'travel', location: 'preview-bedroom' });
  await one.getByRole('button', { name: /Inspect Sample specimen/ }).click();
  await expect(one.getByRole('button', { name: 'Examine the surface', exact: true })).toBeVisible({ timeout: 20000 });
  await expect(one.getByRole('button', { name: 'Turn the sample', exact: true })).toHaveCount(0);
  await one.getByRole('button', { name: 'Examine the surface', exact: true }).click();
  await expect(one.getByText('The surface has a mark.', { exact: true })).not.toBeVisible();
  await one.getByText('Descriptions', { exact: true }).click();
  await expect(one.getByText('The surface has a mark.', { exact: true })).toBeVisible();
  await one.getByText('Descriptions', { exact: true }).click();
  await expect(one.getByRole('button', { name: 'Turn the sample', exact: true })).toBeDisabled();
  await act(second, { type: 'travel', location: 'preview-bedroom' });
  await one.getByRole('button', { name: 'Turn the sample', exact: true }).click();
  await expect(one.getByText('A second mark is visible beneath.', { exact: true })).not.toBeVisible();
  await expect(one.locator('.object-art-hotspot')).toHaveCount(0);
  await one.getByLabel('View examined detail').selectOption('surface');
  await one.getByText('Descriptions', { exact: true }).click();
  await expect(one.getByText('A second mark is visible beneath.', { exact: true })).toBeVisible();
  await one.getByText('Descriptions', { exact: true }).click();
  await one.getByLabel('View examined detail').selectOption('turn');
  const objectView = await one.locator('.object-art-scroll').boundingBox();
  const objectImage = await one.locator('.object-art-frame img').boundingBox();
  assert.ok(objectImage.height <= objectView.height && objectImage.width <= objectView.width, 'The whole object illustration fits before zooming.');
  await one.screenshot({ path: '.qa/framework/object.png' });
  await one.setViewportSize({ width: 390, height: 844 });
  await one.screenshot({ path: '.qa/framework/object-mobile.png' });
  await one.setViewportSize({ width: 1440, height: 1000 });
  await one.getByRole('button', { name: 'Close inspection', exact: true }).click();
  await act(first, { type: 'travel', location: 'preview-mortuary' });
  await one.getByRole('button', { name: /Inspect Handling record/ }).click();
  await expect(one.getByRole('button', { name: 'Read transcription', exact: true })).toBeVisible({ timeout: 20000 });
  await one.getByRole('button', { name: 'Read transcription', exact: true }).click();
  await expect(one.getByRole('article', { name: 'Document transcription' })).toBeVisible();
  await one.getByRole('button', { name: 'Close document', exact: true }).click();
  await expect(one.getByRole('button', { name: 'People', exact: true })).toHaveCount(0);
  await one.getByRole('button', { name: 'Case map', exact: true }).click();
  await one.locator('.react-flow__node[data-id=specimen]').hover();
  await one.getByRole('button', { name: 'Connect Sample specimen', exact: true }).click();
  await one.locator('.react-flow__node[data-id=account]').hover();
  await one.getByRole('button', { name: 'Connect Curator’s account', exact: true }).click();
  await expect(one.getByRole('heading', { name: 'Record the handling sequence' })).toBeVisible();
  const puzzle = await act(first, { type: 'deduce', evidenceIds: ['specimen', 'account'] });
  assert.equal('order' in puzzle.reconstruction, false);
  assert.equal('pairs' in puzzle.reconstruction, false);
  await one.getByRole('button', { name: 'Record this reconstruction', exact: true }).click();
  await expect(one.getByText('Receive the sample, check it, then enter the result.', { exact: true }).first()).toBeVisible();
  await one.getByRole('button', { name: 'Move step 1 later', exact: true }).click();
  await one.getByRole('button', { name: 'Move step 2 later', exact: true }).click();
  await one.getByRole('button', { name: 'Record this reconstruction', exact: true }).click();
  await expect.poll(async () => (await snapshot(first)).deductions).toEqual(['comparison']);
  await one.screenshot({ path: '.qa/framework/case-map.png' });
  await act(first, { type: 'finalReport', findings: ['alone'] });
  assert.equal((await act(second, { type: 'finalReport', findings: ['alone'] })).ok, false);
  assert.equal((await snapshot(first)).chapter.index, 1);
  for (const player of [first, second]) assert.equal((await act(player, { type: 'finalReport', findings: ['together', 'six-places'] })).ok, true);
  await expect(one.getByText('Later that day', { exact: true })).toBeVisible();
  await one.getByRole('button', { name: 'Skip scene together' }).click();
  await two.getByRole('button', { name: 'Agree to skip scene' }).click();
  await expect.poll(async () => (await snapshot(first)).chapter.index).toBe(2);
  assert.equal((await act(first, { type: 'continueStage' })).ok, true);
  assert.equal((await snapshot(first)).phase, 'investigating');
  assert.equal((await act(second, { type: 'continueStage' })).ok, true);
  await expect(one.getByRole('heading', { name: 'Case complete', exact: true })).toBeVisible();
  assert.equal((await snapshot(first)).phase, 'solved');
  await one.reload();
  await expect(one.getByRole('heading', { name: 'Case complete', exact: true })).toBeVisible();
  await one.screenshot({ path: '.qa/framework/ending.png' });
  assert.deepEqual(errors, []);
  console.log('Framework passed: exclusive lobby, two-player start, cutscene turns/reload/reconnect/skip, six destinations, rejected and agreed reports, three stages and saved ending.');
  }
  assert.deepEqual(errors, []);
} catch (error) { await one.screenshot({ path: '.qa/framework/failure.png' }).catch(() => {}); console.error(await one.locator('body').innerText()); console.error('Browser errors:', errors); throw error; } finally { await browser.close(); }
